### ISSUE TITLE
How do we retrieve forces information that we give manually to the Geomagic device?

### ISSUE THREAD

**Issue by misaki43** [robotology/haptic-devices#3]
Hello,

In my program, I want to retrieve forces information given to the geomagic by my hand, that allow the simulated robot to move. But when I retrieve them, I have strange values (see joint picture). Could you help me understand why?  
I have some more specific questions:

1. At the "port-scale" level:
I don't understand how are given forces information that comes from the Geomagic device:
I can only retrieve [x, y, z, ox, oy, oz , button1, button2] information, right? (thanks to /geomagic/state:o port).
I try to retrieve these forces information from the port:
/wholeBodyDynamicsTree/left_arm/cartesianEndEffectorWrench:o
But I read nowhere that wholeBodyDynamicsTree receives the geomagic forces information... Is it correct to do that? If yes what could explain my strange data values ?

2. At your "program-scale" level: 
In your different examples and tests (test-geomagic-* and teleop-icub ), I only found how we can send forces information from the C++ program to the Geomagic, using "setFeedback" function.
But I don't find how I can retrieve forces information from the Geomagic (so, in the other direction). Do I miss something?
Moreover, if I understand correctly, the feedback forces values send to the Geomagic device are just scaled according to "maxFeedback" and "maxForces" variables isn't it? So, how can we interpret these values?

3. In your teleoperation example, from where comes the "/force-feedback:i" port information?

Information:
Here is my code: https://github.com/inria-larsen/icubLearningTrajectories/blob/master/CppProgram/recordTrajectories.cpp
Here is a picture of received forces for a upward movement:
![forces moments](https://cloud.githubusercontent.com/assets/9462576/24657200/a9c89e70-1945-11e7-9473-00862f3c228c.png)

Thank you for your help!

-- 
Oriane Dermy

**Comment by pattacini** [comment]
Hi @misaki43 

Simply, the forces/torques are **not outputs of** Geomagic but rather **inputs to** the device used to elicit a sort of **touch feedback**.

From the Geomagic you can only retrieve information regarding **position** and **orientation** of the end-effector along with the status of the **buttons**.

**Comment by misaki43** [comment]
Hi @pattacini, thank you for this quick answer!
Ok thanks, It is what I was afraid of...

So I assume the problem is the WBDT doesn't compute well the forces information ( #89, #160). 
Time to change to the wholeBodyDynamicsDevice (#223).

**Comment by pattacini** [comment]
Well, I don't know exactly your specific case, but the old glorious `WBD` is still doing its job quite nicely 😉

**Comment by misaki43** [comment]
Hum, may be I do something wrong because my results are not better with WBD:
* If I read directly the port "[...]/cartesianEndEffectorWrench:o", I have these kind of results:
![drawing](https://cloud.githubusercontent.com/assets/9462576/24763485/ce93a314-1af1-11e7-9ae7-485fa4a3e188.png)

* If I want to use functions, I only find how to use torque control but no force control. Do I miss something?

**Comment by traversaro** [comment]
Hi @misaki43 , can you please open an issue on this on the appropriate repository (for example https://github.com/robotology/codyco-modules) and explain in detail your problem? 
I fail to see how any problem in the estimation of external forces performed by WBD and all its descendants is related to the Geomagic.
